org: gabrielcouto26
app: desafio-payface
service: desafio-payface

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SQS_QUEUE_URL:
      Fn::GetAtt: [TransactionQueue, QueueUrl]
    SNS_TOPIC_ARN:
      Ref: SuccessNotificationTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [TransactionQueue, Arn]
            - Fn::GetAtt: [TransactionDLQ, Arn]
        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:Receive
          Resource:
            - Ref: SuccessNotificationTopic
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [NotificationDLQ, Arn]

package:
  individually: true

build:
  esbuild: false

functions:
  sendMoney:
    handler: src/lambda/http.handler
    events:
      - http:
          path: /wallet/send
          method: post

  processTransaction:
    handler: src/lambda/sqs.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [TransactionQueue, Arn]

  notification:
    handler: src/lambda/sns.handler
    events:
      - sns:
          arn:
            Ref: SuccessNotificationTopic
          topicName: success-notification-topic
    onError: arn:aws:sqs:${self:provider.region}:${aws:accountId}:notification-dlq

resources:
  Resources:
    TransactionDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: transaction-dlq

    TransactionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: transaction-queue
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [TransactionDLQ, Arn]
          maxReceiveCount: 2

    NotificationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: notification-dlq

    SuccessNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: success-notification-topic
        DisplayName: Success Notification Topic
