org: gabrielcouto26
app: desafio-payface
service: desafio-payface

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SQS_QUEUE_URL:
      Fn::GetAtt: [TransactionQueue, QueueUrl]
    SNS_TOPIC_ARN:
      Ref: SuccessNotificationTopic
    EMAIL_TOPIC_ARN:
      Ref: EmailNotificationTopic
    DB_HOST:
      Fn::GetAtt: [PostgresDB, Endpoint.Address]
    DB_PORT: 5432
    DB_NAME: payface
    DB_USERNAME: ${self:custom.dbUser}
    DB_PASSWORD: ${self:custom.dbPassword}
    REDIS_URL: ${self:custom.redisUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [TransactionQueue, Arn]
            - Fn::GetAtt: [TransactionDLQ, Arn]
        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:Receive
          Resource:
            - Ref: SuccessNotificationTopic
            - Ref: EmailNotificationTopic
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [NotificationDLQ, Arn]
        - Effect: Allow
          Action:
            - rds-db:connect
          Resource:
            - Fn::GetAtt: [PostgresDB, DBInstanceArn]
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/payface/redis/url
        - Effect: Allow
          Action:
            - elasticache:DescribeReplicationGroups
            - elasticache:DescribeCacheClusters
          Resource: "*"

package:
  individually: true

build:
  esbuild: false

functions:
  sendMoney:
    handler: src/lambda-adapters/http.handler
    events:
      - http:
          path: /wallet/send
          method: post

  processTransaction:
    handler: src/lambda-adapters/sqs.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [TransactionQueue, Arn]

  notification:
    handler: src/lambda-adapters/sns.handler
    events:
      - sns:
          arn:
            Ref: SuccessNotificationTopic
          topicName: success-notification-topic
    onError: arn:aws:sqs:${self:provider.region}:${aws:accountId}:notification-dlq

resources:
  Resources:
    TransactionDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: transaction-dlq

    TransactionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: transaction-queue
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [TransactionDLQ, Arn]
          maxReceiveCount: 2

    NotificationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: notification-dlq

    SuccessNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: success-notification-topic
        DisplayName: Success Notification Topic

    EmailNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: email-notification-topic
        DisplayName: Email Notification Topic

    EmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: gabrielcouto26@gmail.com
        TopicArn:
          Ref: EmailNotificationTopic

    PostgresDB:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: postgres
        DBInstanceClass: db.t3.micro
        AllocatedStorage: 20
        MasterUsername: ${self:custom.dbUser}
        MasterUserPassword: ${self:custom.dbPassword}
        DBName: payface
        PubliclyAccessible: true
        VPCSecurityGroups:
          - Fn::GetAtt: [PostgresSecurityGroup, GroupId]

    PostgresSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for RDS PostgreSQL
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            CidrIp: 0.0.0.0/0

custom:
  dbUser: payface_admin
  dbPassword: ${ssm:/payface/db/password}
  redisUrl: ${ssm:/payface/redis/url}
